# Ref: https://wanago.io/2023/01/16/api-nestjs-docker-compose/

version: '3.8'

services:
  database:
    image: postgres:13-alpine
    restart: always
    networks:
      - postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=for_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
  
  # # enable only when target image exists
  # nest_gql:
  #   image: nest_gql:v1
  #   environment:
  #     - DB_HOST=database
  #   ports:
  #     - "80:3030" 
  #   depends_on:
  #     - database
  #   networks:
  #     - postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge